### ISSUE TITLE
Handling of inline vs block images

### ISSUE THREAD

**Issue by splorp** [splorp/tersus-splorp#4]
Small icons and inline images current have block level styles applied to them. In the following example, the small download link icon breaks the current layout.

[Screenshot](http://cl.ly/KCJM)

One solution would be to use the `:before` pseudoclass and insert file or webfont-based icons inline with links containing specific file type extensions.

``` css
a[href$='.pdf']:before {
   content: url(pdf.gif);
   display: inline-block;
   margin-left: 4px;
   width: 16px;
   height: 16px;
}
```
